// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADu_3JiQN7_WnE3cvf2iXEoqIihgeuEIc',
    appId: '1:29918237301:web:2e61c93f8a2bf12fe79e3c',
    messagingSenderId: '29918237301',
    projectId: 'car-rental03',
    authDomain: 'car-rental03.firebaseapp.com',
    storageBucket: 'car-rental03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5MIzlZWnPRZO8BHhmdPFH5V5F3JOykas',
    appId: '1:29918237301:android:c8516138abcd8729e79e3c',
    messagingSenderId: '29918237301',
    projectId: 'car-rental03',
    storageBucket: 'car-rental03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4y9hY_KwrcS61p3l_-hpxDuZNre5F1sA',
    appId: '1:29918237301:ios:930119d5a8fed3f9e79e3c',
    messagingSenderId: '29918237301',
    projectId: 'car-rental03',
    storageBucket: 'car-rental03.appspot.com',
    iosClientId: '29918237301-aj8ionukk857l1d3aaic636726bu2qeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4y9hY_KwrcS61p3l_-hpxDuZNre5F1sA',
    appId: '1:29918237301:ios:930119d5a8fed3f9e79e3c',
    messagingSenderId: '29918237301',
    projectId: 'car-rental03',
    storageBucket: 'car-rental03.appspot.com',
    iosClientId: '29918237301-aj8ionukk857l1d3aaic636726bu2qeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
