// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADu_3JiQN7_WnE3cvf2iXEoqIihgeuEIc',
    appId: '1:29918237301:web:2e61c93f8a2bf12fe79e3c',
    messagingSenderId: '29918237301',
    projectId: 'car-rental03',
    authDomain: 'car-rental03.firebaseapp.com',
    storageBucket: 'car-rental03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5MIzlZWnPRZO8BHhmdPFH5V5F3JOykas',
    appId: '1:29918237301:android:5033ecd2757c2c0fe79e3c',
    messagingSenderId: '29918237301',
    projectId: 'car-rental03',
    storageBucket: 'car-rental03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4y9hY_KwrcS61p3l_-hpxDuZNre5F1sA',
    appId: '1:29918237301:ios:f464280c05e2e494e79e3c',
    messagingSenderId: '29918237301',
    projectId: 'car-rental03',
    storageBucket: 'car-rental03.appspot.com',
    iosClientId: '29918237301-htk6q5e068hikhtsuerciq8jdoj719ol.apps.googleusercontent.com',
    iosBundleId: 'dz.walid.plus',
  );
}
